### ISSUE TITLE
Update Meta tags

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/reVISit-studies.github.io#39]
Add meta tags so that when revisit is linked it expands to relevant context. Example: 

Home meta could be: "reVISit: Reproducible and Powerful Visualization User Studies" 

https://vdl.sci.utah.edu/ 

<img width="503" alt="image" src="https://github.com/revisit-studies/reVISit-studies.github.io/assets/2039375/2e5780bc-25e0-4a5c-8030-fd4a78bb99e1">

Where appropriate, the meta tags could be more verbose, like here: 
<img width="654" alt="image" src="https://github.com/revisit-studies/reVISit-studies.github.io/assets/2039375/4e66ac55-35d7-4bd3-95a7-0c49890a1483">

**Comment by bbollen23** [comment]
Fixed in 5bf5150bea86e1b98a526077656f4d2732c24927

To edit the description, you can go into `docusaurus.config.ts` and edit the `config.tagline` value.
