### ISSUE TITLE
Missing info about VITE_REVISIT_MODE in firebase

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/reVISit-studies.github.io#44]
Adding something about `VITE_REVISIT_MODE` from .env to 'Connecting to Firebase'. About 3 weeks ago `VITE_REVISIT_MODE` was added in the .env file and if it is set to 'public' then 'src/storage/initialize.ts' always uses the Local Storage engine. I just changed it to 'firebase' and everything worked fine.

**Comment by bbollen23** [comment]
Closing since we are removing this.
