### ISSUE TITLE
Links break after clicking an anchor

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/reVISit-studies.github.io#50]
In some scenarios, links for pages are produced with a trailing slash, in others they are not

For example if you click on how does it work in the docs through the menu you get to:
https://revisit.dev/docs/getting-started/how-does-it-work

If you then click on the study metadata link at the end of the Study Metadata documentation paragraph it works and links here.
https://revisit.dev/docs/typedoc/interfaces/StudyMetadata

In some odd scenarios, however, you get to 
https://revisit.dev/docs/getting-started/how-does-it-work/ 

The easiest way I've found to reproduce this is to reload the page, which will add the `/` in chrome. 

At that point the ../ doesn't go back up enough, resulting in dead links

2 possible solutions: 
* fix the / thing - either always have it or never 
* use a base url variable relative to root instead of `../` That might be more robust in general.

**Comment by JackWilb** [comment]
Fixed on prod by mandating that all pages have a trailing slash. This is consistent with the GitHub Pages defaults
